using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Fragsurf.Movement;
using Cinemachine;

public class Cache : MonoBehaviour
{
    public static SurfCharacter surfCharacter;
    public static MoveData moveData;
    public static Transform mainCam;
    public static VelocityManager velocityManager;
    public static Rigidbody rb;
    public static Collider col;
    public static FragMovementManager fragMovementManager;
    public static CameraWorldSpaceRotationOffsetManager cameraWorldSpaceRotationOffsetManager;
    public static GravityManager gravityManager;
    public static RunBob runBob;
    public static JumpHeightManager jumpHeightManagerScript;
    public static CinemachineVirtualCamera vcam;
    public static FovManager fovManager;
    public static PlayerColliderSizeManager playerColliderSizeManager;
    public static Swinger swinger;
    public static Wallrunner wallrunner;
    public static ThirdPersonCharacterRenderManager thirdPersonCharacterRenderManager;
    public static ColliderCornerCaster colliderCornerCaster;
    public static CameraLocalPositionOffsetManager cameraLocalPositionOffsetManager;
    public static Vaulter vaulter;
    public static PlayerAnimator playerAnimator;
    public static VaultBob vaultBob;
    public static ArmManager armManager;
    public static LongJump longJump;
    public static Wallclimber wallclimber;
    public static Slide slide;
    public static WalkSpeedManager walkSpeedManager;
    public static CamViewOffsetManager camViewOffsetManager;
    public static CameraBobManager camBobManager;
    public static CameraRotationOffsetManager cameraRotationOffsetManager;
    public static MouseSensitivityManager mouseSensitivityManager;
    public static Ammo ammo;
    public static References references;
    public static GrenadeManager grenadeManager;
    public static Health health;
    public static Crouch crouch;
    public static InstanceManagement instanceManagement;
    public static SpeedCounter speedCounter;
    public static Terminal terminal;
    public static SpreadCounter spreadCounter;
    public static SkyManager skyManager;
    public static CavityManager cavityManager;
    public static DebugViewNormalsManager debugViewNormalsManager;
    public static DebugViewOnlyCavityManager debugViewOnlyCavityManager;
    public static ObjectRunBob itemRunBobManager;
    public static GameObject gameScripts;
    public static FallDamage fallDamage;
    public static HitMarkerManager hitMarkerManager;
    public static InventoryUIManager inventoryUIManager;
    public static ConfigSettings configSettings;
    public static AudioVolumeManager audioVolumeManager;
    public static Inventory inventory;
    public static PackageLoader packageLoader;
    public static RunCommandOnLevel runCommandOnLevel;
    public static Client client;
    public static OnlineProxyIn onlineProxyIn;
    public static OnlineProxyOut onlineProxyOut;
    public static OnlineWorldManager onlineWorldManager;
    public static CamFovManager handheldRenderFovManager;
    public static FirearmSpreadCrosshairIndicator firearmSpreadCrosshairIndicator;
    public static Crouch16 crouch16;
    public static FogManager fogManager;
    public static Inspect inspect;
    public static HideUI hideUi;
    public static CinemachineBrain cinemachineBrain;
    public static ActiveVcamManager activeVcamManager;
    public static CanonTimeManager canonTimeManager;
    public static SubtitleManager subtitleManager;
    public static AmbienceTrackManager ambienceTrackManager;
    public static InstanceAmbienceTracks instanceAmbienceTracks;
    public static AmbienceManager ambienceManager;
    public static ResetSequenceOnRespawn resetSequenceOnRespawn;
    public static RectTransform dynamicCanvas;
    public static Escape escape;
    public static Stabilize stabilize;
    public static SetLoadedInstancesOnRespawn setLoadedInstancesOnRespawn;

    public static Vector3 respawnPos;
    //public static Camera playerCamera;
}
